### ISSUE TITLE
Latest Releases Are Missing Webupd8 Changes Files

### ISSUE THREAD

**Issue by ngamradt-turner** [evpo/EncryptPad#118]
Thanks for this great little tool!

I noticed that the last couple of releases are missing the latest Webupd8 changes files.

If you look at this release...

https://github.com/evpo/EncryptPad/releases/tag/v0.5.0.1

...it doesn't have the Webupd8 changes files like this older release has:

https://github.com/evpo/EncryptPad/releases/tag/v0.4.0.4

Without these release files, you cannot complete the verification process outlined here:

https://github.com/evpo/EncryptPad#integrity-verification-procedure

Guessing perhaps part of the process has just broken?

**Comment by ngamradt-turner** [comment]
Hello @evpo , thank you so much.  In the meantime, is there an alternative way to verify the existing release?

**Comment by evpo** [comment]
Since our communication the ppa process has changed (see https://github.com/evpo/EncryptPad#install-on-ubuntu) . I maintain my own ppa and the extra verification does not make sense anymore. The process of building ppa relies on the Canonical infrastructure and my own configuration which I sign when I submit it to the build servers.
