### ISSUE TITLE
Make the number of saved keys genrated by S2K configurable in Preferences

### ISSUE THREAD

**Issue by evpo** [evpo/EncryptPad#41]
Currently there are five keys. This number is too small for some users (see #40).

**Comment by mkrier** [comment]
You're saying I have to compile it? I've never compiled it, I just installed the windows exe.  

Look, I'm only one user but... I might just be the squeaky wheel.  Here- look at it like this- the only way I can use this editor is to keep the password in a separate, open, text file.   Because I have to enter it so often than I'll just copy and paste it.  Oh, I've memorized it, sure, but nonetheless, typing it every 20 minutes or whatever is so annoying that either I stop using encryptpad or save the pw to a file.  

It's like you're thinking in terms of math and not in terms of humans. Metaphorically it's like forgetting that a hacker can use social engineering.  You're pushing the user into doing something unsafe. "Security" isn't only just math.

Well, and/or I make the password something easy to type.  Also bad.  

See, you're forgetting the human aspect.

But again, I'm only one user.

**Comment by evpo** [comment]
No, I agree with your point. Please read the comments above. I made another issue #40. It's highest priority and you will be able to configure this number in the next release.

**Comment by evpo** [comment]
I closed #40 and opened #41 because it's more specific.

**Comment by mkrier** [comment]
Oh thanks for being receptive, and sorry I got 40 and 41 confused. 

(Btw, if it matters- I'm actually a programmer as well-  I have 18 years of software development experience; I'm an old-timer.  So, I dunno, I could recompile it, but for now I'll just copy-paste until the next release! )

Thanks, anything more you need from me, lemme know.

**Comment by evpo** [comment]
The enhancement has been implemented in `work` branch. It will be merged to master after testing.

**Comment by evpo** [comment]
Merged to master. It will be part of 0.3.2.4 release
