### ISSUE TITLE
Open GPG armored files...

### ISSUE THREAD

**Issue by martin-langhoff** [evpo/EncryptPad#9]
All gpg actions right now seem to break when they encounter "armored" GPG files.

**Comment by evpo** [comment]
yes, ASCII armor is not supported for anything except key files. It should be relatively easy to implement. It is on my list of improvements.

**Comment by vatterspun** [comment]
Can the program save to ASCII armored files?   At least one person was asking about this: https://www.portablefreeware.com/forums/viewtopic.php?p=91381#p91381

**Comment by evpo** [comment]
Hi @vatterspun ,
Not yet, however, it is relatively easy change. All dependencies are available and ascii is even used for key files. Having said that, the priority of the feature is under question. Although many people ask, I don't know which tool exactly or scenario requires ascii. Do you have any particular service on your mind?

**Comment by vatterspun** [comment]
> Not yet, however, it is relatively easy change. All dependencies are available and ascii is even used for key files. 

Ah good news.

> Having said that, the priority of the feature is under question. Although many people ask, I don't know which tool exactly or scenario requires ascii. 

It's far from crucial so maybe put this down the list of TODOLIST items on this project.  Still, I'd argue that access to encrypted data is equally important to good security.  You can have the most secure protocols and in the universe, but if you don't have easy access to the files and standard decryption tools, it doesn't mean much.  It's been a few years since I've tested it, but I wouldn't be surprised if some Android GPG tools were more friendly to armored text than they are encrypted files.

Plus, you can look through an old archive and easily see an armored text file, whereas a poorly named encrypted file (e.g. doesn't have a .gpg suffix) may go unnoticed.

That said, armored text is certainly less space-efficient than binary ones, so I can't argue that this should be the default.

> Do you have any particular service on your mind?

The one that comes to mind is SimpleText.com, but I know there are multiple text-only sync services for handling text/note synchronization between devices.

**Comment by evpo** [comment]
implemented in armor branch

**Comment by vatterspun** [comment]
Just tested -- where's that function?  I thought I had some ascii-armored text files but I can't seem to find one.

Is there a save-to-ascii armored option yet or is that separate?  I tried saving to .GPG but it's clearly a binary file, and .TXT seems to be the same output.

**Comment by evpo** [comment]
I suspect you are using one of the previous binaries. The feature is in the master branch. I am about to prepare binaries for version 0.5. Building from source is required to get the functionality right now.
